import random
num = list(range(1, 100))
jokes = ["Oh Prime number, it's kind of odd, isn't it? ",
         "People scared of me, why am I odd...", 
         "Why is six scared of seven? ",
         "Why did the two fours skip lunch?",
         "What do you call numbers that don't stay in place?"]

myJokes = {}

for x in num:
    myJokes[x] = random.choice(jokes)

# myJokes = {
#     "1" : "Odd number",
#     "2" : "Even number",
#     "3" : "Odd number",
#     "4" : "Even number",
#     "5" : "Odd number",
#     "6" : "Even number",
#     "7" : "Odd number",
#     "8" : "Even number",
#     "9" : "Odd number",
#     "10" : "Even number",
#     "11" : "Odd number",
#     "12" : "Even number",
#     "13" : "Odd number",
#     "14" : "Even number",
#     "15" : "Odd number",
#     "16" : "Even number",
#     "17" : "Odd number",
#     "18" : "Even number",
#     "19" : "Odd number",
#     "20" : "Even number",
#     "21" : "Odd number",
#     "22" : "Even number",
#     "23" : "Odd number",
#     "24" : "Even number",
#     "25" : "Odd number",
#     "26" : "Even number",
#     "27" : "Odd number",
#     "28" : "Even number",
#     "29" : "Odd number",
#     "30" : "Even number",
#     "31" : "Odd number",
#     "32" : "Even number",
#     "33" : "Odd number",
#     "34" : "Even number",
#     "35" : "Odd number",
#     "36" : "Even number",
#     "37" : "Odd number",
#     "38" : "Even number",
#     "39" : "Odd number",
#     "40" : "Even number",
#     "41" : "Odd number",
#     "42" : "Even number",
#     "43" : "Odd number",
#     "44" : "Even number",
#     "45" : "Odd number",
#     "46" : "Even number",
#     "47" : "Odd number",
#     "48" : "Even number",
#     "49" : "Odd number",
#     "50" : "Even number",
#     "51" : "Odd number",
#     "52" : "Even number",
#     "53" : "Odd number",
#     "54" : "Even number",
#     "55" : "Odd number",
#     "56" : "Even number",
#     "57" : "Odd number",
#     "58" : "Even number",
#     "59" : "Odd number",
#     "60" : "Even number",
#     "61" : "Odd number",
#     "62" : "Even number",
#     "63" : "Odd number",
#     "64" : "Even number",
#     "65" : "Odd number",
#     "66" : "Even number",
#     "67" : "Odd number",
#     "68" : "Even number",
#     "69" : "Odd number",
#     "70" : "Even number",
#     "71" : "Odd number",
#     "72" : "Even number",
#     "73" : "Odd number",
#     "74" : "Even number",
#     "75" : "Odd number",
#     "76" : "Even number",
#     "77" : "Odd number",
#     "78" : "Even number",
#     "79" : "Odd number",
#     "80" : "Even number",
#     "81" : "Odd number",
#     "82" : "Even number",
#     "83" : "Odd number",
#     "84" : "Even number",
#     "85" : "Odd number",
#     "86" : "Even number",
#     "87" : "Odd number",
#     "88" : "Even number",
#     "89" : "Odd number",
#     "90" : "Even number",
#     "91" : "Odd number",
#     "92" : "Even number",
#     "93" : "Odd number",
#     "94" : "Even number",
#     "95" : "Odd number",
#     "96" : "Even number",
#     "97" : "Odd number",
#     "98" : "Even number",
#     "99" : "Odd number",
#     "100" : "Even number"
# }
selection = int(input("Your favourites number between 1 to 100: "))
if selection in myJokes:
    print(myJokes[selection])
else:
    print("Please select between 1 and 100. ")
